### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by jlx2021** [no-body-in-particular/NoVNCAudio#2]
Hello, I encountered these errors during “make”. May I ask if I should update the gcc version. The current version is gcc4.8.5
![Snipaste_2023-07-17_17-15-09](https://github.com/no-body-in-particular/NoVNCAudio/assets/89242177/69addd39-b2d9-407b-8313-e9f2c11acb38)

**Comment by no-body-in-particular** [comment]
What architecture are you building on, and can I have the whole output of the make command? This software will only build correctly on Linux.

**Comment by no-body-in-particular** [comment]
Also your GCC is kind of *really* old: gcc (Gentoo 13.1.1_p20230527 p3) 13.1.1 20230527 is what i'm building with.
