### ISSUE TITLE
Need for clarification.

### ISSUE THREAD

**Issue by Sillylittleguy1** [no-body-in-particular/NoVNCAudio#4]
while for some the instructions are clear, me, myself, and i, cannot comprehend them. 
First off; is this supposed to be run alongside noVNC or a replacement with audio?
Secondly; can you provide some clearer info on what files go where, as i cant find them for my install.

[thanks in advance]

**Comment by no-body-in-particular** [comment]
the folder structure largely matches what gets stored on your device - it's supposed to run alongside noVNC - on a linux host with x11vnc. binaries will install themselves when you use "make install" - the bin and etc folder need to be copied to your system manually.
